services:
  database:
    container_name: mysql-sql-springChat
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springChat
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - springChat
    restart: unless-stopped

  keycloak:
    container_name: keycloak-springChat
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - springChat
    command:
      - "start-dev"

networks:
  springChat:
    driver: bridge

volumes:
  mysql:
    driver: local
